"""Mnemonic enum and display strings, generated by tools/gen_mnemonics.py.

Do not edit by hand. See `pydasm/mnemonic.py` for the behavioural helpers.
"""

from __future__ import annotations

import enum


class Mnemonic(enum.Enum):
    """x86 mnemonics. Order mirrors marty_dasm's Rust enum."""

    Invalid = 'Invalid'
    NoOpcode = 'NoOpcode'
    Group = 'Group'
    Extension = 'Extension'
    Prefix = 'Prefix'
    NOP = 'NOP'
    AAA = 'AAA'
    AAD = 'AAD'
    AAM = 'AAM'
    AAS = 'AAS'
    ADC = 'ADC'
    ADD = 'ADD'
    AND = 'AND'
    CALL = 'CALL'
    CALLF = 'CALLF'
    CBW = 'CBW'
    CLC = 'CLC'
    CLD = 'CLD'
    CLI = 'CLI'
    CMC = 'CMC'
    CMP = 'CMP'
    CMPSB = 'CMPSB'
    CMPSW = 'CMPSW'
    CMPSD = 'CMPSD'
    CWD = 'CWD'
    CDQ = 'CDQ'
    CWDE = 'CWDE'
    DAA = 'DAA'
    DAS = 'DAS'
    DEC = 'DEC'
    DIV = 'DIV'
    ESC = 'ESC'
    WAIT = 'WAIT'
    HLT = 'HLT'
    IDIV = 'IDIV'
    IMUL = 'IMUL'
    IN = 'IN'
    INC = 'INC'
    INT = 'INT'
    INT1 = 'INT1'
    INT3 = 'INT3'
    INTO = 'INTO'
    IRET = 'IRET'
    IRETW = 'IRETW'
    IRETD = 'IRETD'
    JB = 'JB'
    JBE = 'JBE'
    JCXZ = 'JCXZ'
    JECXZ = 'JECXZ'
    JL = 'JL'
    JLE = 'JLE'
    JMP = 'JMP'
    JMPF = 'JMPF'
    JNB = 'JNB'
    JNBE = 'JNBE'
    JNL = 'JNL'
    JNLE = 'JNLE'
    JNO = 'JNO'
    JNP = 'JNP'
    JNS = 'JNS'
    JNZ = 'JNZ'
    JO = 'JO'
    JP = 'JP'
    JS = 'JS'
    JZ = 'JZ'
    LAHF = 'LAHF'
    LDS = 'LDS'
    LEA = 'LEA'
    LES = 'LES'
    LOCK = 'LOCK'
    LODSB = 'LODSB'
    LODSW = 'LODSW'
    LODSD = 'LODSD'
    LOOP = 'LOOP'
    LOOPNE = 'LOOPNE'
    LOOPE = 'LOOPE'
    MOV = 'MOV'
    UMOV = 'UMOV'
    MOVSB = 'MOVSB'
    MOVSW = 'MOVSW'
    MOVSD = 'MOVSD'
    MUL = 'MUL'
    NEG = 'NEG'
    NOT = 'NOT'
    OR = 'OR'
    OUT = 'OUT'
    POP = 'POP'
    POPF = 'POPF'
    POPFW = 'POPFW'
    POPFD = 'POPFD'
    PUSH = 'PUSH'
    PUSHF = 'PUSHF'
    PUSHFW = 'PUSHFW'
    PUSHFD = 'PUSHFD'
    RCL = 'RCL'
    RCR = 'RCR'
    REP = 'REP'
    REPNE = 'REPNE'
    REPE = 'REPE'
    RETF = 'RETF'
    RETFW = 'RETFW'
    RETFD = 'RETFD'
    RET = 'RET'
    RETW = 'RETW'
    RETD = 'RETD'
    ROL = 'ROL'
    ROR = 'ROR'
    SAHF = 'SAHF'
    SALC = 'SALC'
    SAR = 'SAR'
    SBB = 'SBB'
    SCASB = 'SCASB'
    SCASW = 'SCASW'
    SCASD = 'SCASD'
    SETMO = 'SETMO'
    SETMOC = 'SETMOC'
    SHL = 'SHL'
    SHR = 'SHR'
    SAL = 'SAL'
    STC = 'STC'
    STD = 'STD'
    STI = 'STI'
    STOSB = 'STOSB'
    STOSW = 'STOSW'
    STOSD = 'STOSD'
    SUB = 'SUB'
    TEST = 'TEST'
    XCHG = 'XCHG'
    XLAT = 'XLAT'
    XOR = 'XOR'
    PUSHA = 'PUSHA'
    PUSHAW = 'PUSHAW'
    PUSHAD = 'PUSHAD'
    POPA = 'POPA'
    POPAW = 'POPAW'
    POPAD = 'POPAD'
    BOUND = 'BOUND'
    INSB = 'INSB'
    INSW = 'INSW'
    INSD = 'INSD'
    OUTSB = 'OUTSB'
    OUTSW = 'OUTSW'
    OUTSD = 'OUTSD'
    ENTER = 'ENTER'
    LEAVE = 'LEAVE'
    UNDEF = 'UNDEF'
    FPO2 = 'FPO2'
    TEST1 = 'TEST1'
    CLR1 = 'CLR1'
    SET1 = 'SET1'
    NOT1 = 'NOT1'
    ADD4S = 'ADD4S'
    SUB4S = 'SUB4S'
    CMP4S = 'CMP4S'
    ROL4 = 'ROL4'
    ROR4 = 'ROR4'
    BINS = 'BINS'
    BEXT = 'BEXT'
    BRKEM = 'BRKEM'
    ARPL = 'ARPL'
    SLDT = 'SLDT'
    STR = 'STR'
    LLDT = 'LLDT'
    LTR = 'LTR'
    VERR = 'VERR'
    VERW = 'VERW'
    SGDT = 'SGDT'
    SIDT = 'SIDT'
    LGDT = 'LGDT'
    LIDT = 'LIDT'
    SMSW = 'SMSW'
    LMSW = 'LMSW'
    LAR = 'LAR'
    LSL = 'LSL'
    CLTS = 'CLTS'
    LOADALL = 'LOADALL'
    UD2 = 'UD2'
    UD1 = 'UD1'
    UD0 = 'UD0'
    SETO = 'SETO'
    SETNO = 'SETNO'
    SETB = 'SETB'
    SETNB = 'SETNB'
    SETZ = 'SETZ'
    SETNZ = 'SETNZ'
    SETBE = 'SETBE'
    SETNBE = 'SETNBE'
    SETS = 'SETS'
    SETNS = 'SETNS'
    SETP = 'SETP'
    SETNP = 'SETNP'
    SETL = 'SETL'
    SETNL = 'SETNL'
    SETLE = 'SETLE'
    SETNLE = 'SETNLE'
    SHLD = 'SHLD'
    SHRD = 'SHRD'
    RSM = 'RSM'
    BT = 'BT'
    BTC = 'BTC'
    BTS = 'BTS'
    BTR = 'BTR'
    BSF = 'BSF'
    BSR = 'BSR'
    LSS = 'LSS'
    LFS = 'LFS'
    LGS = 'LGS'
    MOVZX = 'MOVZX'
    MOVSX = 'MOVSX'


MNEMONIC_STR: dict[Mnemonic, str] = {
    Mnemonic.NOP: 'NOP',
    Mnemonic.AAA: 'AAA',
    Mnemonic.AAD: 'AAD',
    Mnemonic.AAM: 'AAM',
    Mnemonic.AAS: 'AAS',
    Mnemonic.ADC: 'ADC',
    Mnemonic.ADD: 'ADD',
    Mnemonic.AND: 'AND',
    Mnemonic.CALL: 'CALL',
    Mnemonic.CALLF: 'CALL',
    Mnemonic.CBW: 'CBW',
    Mnemonic.CLC: 'CLC',
    Mnemonic.CLD: 'CLD',
    Mnemonic.CLI: 'CLI',
    Mnemonic.CMC: 'CMC',
    Mnemonic.CMP: 'CMP',
    Mnemonic.CMPSB: 'CMPSB',
    Mnemonic.CMPSW: 'CMPSW',
    Mnemonic.CMPSD: 'CMPSD',
    Mnemonic.CWD: 'CWD',
    Mnemonic.CDQ: 'CDQ',
    Mnemonic.CWDE: 'CWDE',
    Mnemonic.DAA: 'DAA',
    Mnemonic.DAS: 'DAS',
    Mnemonic.DEC: 'DEC',
    Mnemonic.DIV: 'DIV',
    Mnemonic.ESC: 'ESC',
    Mnemonic.WAIT: 'WAIT',
    Mnemonic.HLT: 'HLT',
    Mnemonic.IDIV: 'IDIV',
    Mnemonic.IMUL: 'IMUL',
    Mnemonic.IN: 'IN',
    Mnemonic.INC: 'INC',
    Mnemonic.INT: 'INT',
    Mnemonic.INT1: 'INT1',
    Mnemonic.INT3: 'INT3',
    Mnemonic.INTO: 'INTO',
    Mnemonic.IRET: 'IRET',
    Mnemonic.IRETW: 'IRETW',
    Mnemonic.IRETD: 'IRETD',
    Mnemonic.JB: 'JB',
    Mnemonic.JBE: 'JBE',
    Mnemonic.JCXZ: 'JCXZ',
    Mnemonic.JECXZ: 'JECXZ',
    Mnemonic.JL: 'JL',
    Mnemonic.JLE: 'JLE',
    Mnemonic.JMP: 'JMP',
    Mnemonic.JMPF: 'JMP',
    Mnemonic.JNB: 'JNB',
    Mnemonic.JNBE: 'JNBE',
    Mnemonic.JNL: 'JNL',
    Mnemonic.JNLE: 'JNLE',
    Mnemonic.JNO: 'JNO',
    Mnemonic.JNP: 'JNP',
    Mnemonic.JNS: 'JNS',
    Mnemonic.JNZ: 'JNZ',
    Mnemonic.JO: 'JO',
    Mnemonic.JP: 'JP',
    Mnemonic.JS: 'JS',
    Mnemonic.JZ: 'JZ',
    Mnemonic.LAHF: 'LAHF',
    Mnemonic.LDS: 'LDS',
    Mnemonic.LEA: 'LEA',
    Mnemonic.LES: 'LES',
    Mnemonic.LOCK: 'LOCK',
    Mnemonic.LODSB: 'LODSB',
    Mnemonic.LODSW: 'LODSW',
    Mnemonic.LODSD: 'LODSD',
    Mnemonic.LOOP: 'LOOP',
    Mnemonic.LOOPNE: 'LOOPNE',
    Mnemonic.LOOPE: 'LOOPE',
    Mnemonic.MOV: 'MOV',
    Mnemonic.UMOV: 'UMOV',
    Mnemonic.MOVSB: 'MOVSB',
    Mnemonic.MOVSW: 'MOVSW',
    Mnemonic.MOVSD: 'MOVSD',
    Mnemonic.MUL: 'MUL',
    Mnemonic.NEG: 'NEG',
    Mnemonic.NOT: 'NOT',
    Mnemonic.OR: 'OR',
    Mnemonic.OUT: 'OUT',
    Mnemonic.POP: 'POP',
    Mnemonic.POPF: 'POPF',
    Mnemonic.POPFW: 'POPFW',
    Mnemonic.POPFD: 'POPFD',
    Mnemonic.PUSH: 'PUSH',
    Mnemonic.PUSHF: 'PUSHF',
    Mnemonic.PUSHFW: 'PUSHFW',
    Mnemonic.PUSHFD: 'PUSHFD',
    Mnemonic.RCL: 'RCL',
    Mnemonic.RCR: 'RCR',
    Mnemonic.REP: 'REP',
    Mnemonic.REPNE: 'REPNE',
    Mnemonic.REPE: 'REPE',
    Mnemonic.RETF: 'RETF',
    Mnemonic.RETFW: 'RETFW',
    Mnemonic.RETFD: 'RETFD',
    Mnemonic.RET: 'RET',
    Mnemonic.RETW: 'RETW',
    Mnemonic.RETD: 'RETD',
    Mnemonic.ROL: 'ROL',
    Mnemonic.ROR: 'ROR',
    Mnemonic.SAHF: 'SAHF',
    Mnemonic.SALC: 'SALC',
    Mnemonic.SAR: 'SAR',
    Mnemonic.SBB: 'SBB',
    Mnemonic.SCASB: 'SCASB',
    Mnemonic.SCASW: 'SCASW',
    Mnemonic.SCASD: 'SCASD',
    Mnemonic.SETMO: 'SETMO',
    Mnemonic.SETMOC: 'SETMOC',
    Mnemonic.SHL: 'SHL',
    Mnemonic.SHR: 'SHR',
    Mnemonic.SAL: 'SAL',
    Mnemonic.STC: 'STC',
    Mnemonic.STD: 'STD',
    Mnemonic.STI: 'STI',
    Mnemonic.STOSB: 'STOSB',
    Mnemonic.STOSW: 'STOSW',
    Mnemonic.STOSD: 'STOSD',
    Mnemonic.SUB: 'SUB',
    Mnemonic.TEST: 'TEST',
    Mnemonic.XCHG: 'XCHG',
    Mnemonic.XLAT: 'XLATB',
    Mnemonic.XOR: 'XOR',
    Mnemonic.PUSHA: 'PUSHA',
    Mnemonic.PUSHAW: 'PUSHAW',
    Mnemonic.PUSHAD: 'PUSHAD',
    Mnemonic.POPA: 'POPA',
    Mnemonic.POPAW: 'POPAW',
    Mnemonic.POPAD: 'POPAD',
    Mnemonic.BOUND: 'BOUND',
    Mnemonic.INSB: 'INSB',
    Mnemonic.INSW: 'INSW',
    Mnemonic.INSD: 'INSD',
    Mnemonic.OUTSB: 'OUTSB',
    Mnemonic.OUTSW: 'OUTSW',
    Mnemonic.OUTSD: 'OUTSD',
    Mnemonic.ENTER: 'ENTER',
    Mnemonic.LEAVE: 'LEAVE',
    Mnemonic.FPO2: 'FPO2',
    Mnemonic.TEST1: 'TEST1',
    Mnemonic.CLR1: 'CLR1',
    Mnemonic.SET1: 'SET1',
    Mnemonic.NOT1: 'NOT1',
    Mnemonic.ADD4S: 'ADD4S',
    Mnemonic.SUB4S: 'SUB4S',
    Mnemonic.CMP4S: 'CMP4S',
    Mnemonic.ROL4: 'ROL4',
    Mnemonic.ROR4: 'ROR4',
    Mnemonic.BINS: 'BINS',
    Mnemonic.BEXT: 'BEXT',
    Mnemonic.BRKEM: 'BRKEM',
    Mnemonic.ARPL: 'ARPL',
    Mnemonic.SLDT: 'SLDT',
    Mnemonic.STR: 'STR',
    Mnemonic.LLDT: 'LLDT',
    Mnemonic.LTR: 'LTR',
    Mnemonic.VERR: 'VERR',
    Mnemonic.VERW: 'VERW',
    Mnemonic.SGDT: 'SGDT',
    Mnemonic.SIDT: 'SIDT',
    Mnemonic.LGDT: 'LGDT',
    Mnemonic.LIDT: 'LIDT',
    Mnemonic.SMSW: 'SMSW',
    Mnemonic.LMSW: 'LMSW',
    Mnemonic.LAR: 'LAR',
    Mnemonic.LSL: 'LSL',
    Mnemonic.CLTS: 'CLTS',
    Mnemonic.LOADALL: 'LOADALL',
    Mnemonic.UD2: 'UD2',
    Mnemonic.UD1: 'UD1',
    Mnemonic.UD0: 'UD0',
    Mnemonic.SETO: 'SETO',
    Mnemonic.SETNO: 'SETNO',
    Mnemonic.SETB: 'SETB',
    Mnemonic.SETNB: 'SETNB',
    Mnemonic.SETZ: 'SETZ',
    Mnemonic.SETNZ: 'SETNZ',
    Mnemonic.SETBE: 'SETBE',
    Mnemonic.SETNBE: 'SETNBE',
    Mnemonic.SETS: 'SETS',
    Mnemonic.SETNS: 'SETNS',
    Mnemonic.SETP: 'SETP',
    Mnemonic.SETNP: 'SETNP',
    Mnemonic.SETL: 'SETL',
    Mnemonic.SETNL: 'SETNL',
    Mnemonic.SETLE: 'SETLE',
    Mnemonic.SETNLE: 'SETNLE',
    Mnemonic.SHLD: 'SHLD',
    Mnemonic.SHRD: 'SHRD',
    Mnemonic.RSM: 'RSM',
    Mnemonic.BT: 'BT',
    Mnemonic.BTC: 'BTC',
    Mnemonic.BTS: 'BTS',
    Mnemonic.BTR: 'BTR',
    Mnemonic.BSF: 'BSF',
    Mnemonic.BSR: 'BSR',
    Mnemonic.LSS: 'LSS',
    Mnemonic.LFS: 'LFS',
    Mnemonic.LGS: 'LGS',
    Mnemonic.MOVZX: 'MOVZX',
    Mnemonic.MOVSX: 'MOVSX',
}

MNEMONIC_FALLBACK = 'INVALID'
