#!/usr/bin/env python3
"""Generate `pydasm/_mnemonics.py` from marty_dasm's Rust `mnemonic.rs`.

The Mnemonic enum and its display strings are pure data; this reads them out of
the reference source so the port cannot silently drop or rename a mnemonic.
The behavioural helpers (`is_jump`, `o32_override`, ...) live in the
hand-written `pydasm/mnemonic.py`.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ENUM_RE = re.compile(r"pub enum Mnemonic \{(.*?)\n\}", re.S)
MAP_RE = re.compile(r"match op \{(.*?)\n    \}", re.S)
IDENT_RE = re.compile(r"^[A-Z][A-Za-z0-9_]*$")
ENTRY_RE = re.compile(r"^\s*([A-Z][A-Za-z0-9_]*)\s*=>\s*\"([^\"]*)\",\s*$")


def parse(source: str) -> tuple[list[str], dict[str, str], str]:
    """Read the enum variants, their display strings, and the fallback.

    Exposed so `tests/test_generated_tables_match_source.py` can re-derive the
    table with the same parser the generator uses, instead of a second
    implementation that could drift from it.
    """
    body = ENUM_RE.search(source).group(1)
    variants: list[str] = []
    for raw in body.splitlines():
        line = raw.split("//")[0].strip()
        if not line or line.startswith("#["):
            continue
        name = line.rstrip(",").strip()
        if not IDENT_RE.match(name):
            raise ValueError(f"unexpected enum variant line: {raw!r}")
        if name in variants:
            raise ValueError(f"duplicate variant: {name}")
        variants.append(name)

    map_body = MAP_RE.search(source).group(1)
    strings: dict[str, str] = {}
    for line in map_body.splitlines():
        match = ENTRY_RE.match(line)
        if match:
            strings[match.group(1)] = match.group(2)

    fallback = re.search(r'_\s*=>\s*"([^"]*)"', map_body)
    if fallback is None:
        raise ValueError("no fallback arm found in mnemonic_to_str")
    return variants, strings, fallback.group(1)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    variants, strings, fallback_text = parse(Path(sys.argv[1]).read_text(encoding="utf-8"))

    out = [
        '"""Mnemonic enum and display strings, generated by tools/gen_mnemonics.py.\n',
        "\n",
        "Do not edit by hand. See `pydasm/mnemonic.py` for the behavioural helpers.\n",
        '"""\n',
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "import enum\n",
        "\n",
        "\n",
        "class Mnemonic(enum.Enum):\n",
        '    """x86 mnemonics. Order mirrors marty_dasm\'s Rust enum."""\n',
        "\n",
    ]
    for name in variants:
        out.append(f"    {name} = {name!r}\n")
    out.append("\n\nMNEMONIC_STR: dict[Mnemonic, str] = {\n")
    for name in variants:
        if name in strings:
            out.append(f"    Mnemonic.{name}: {strings[name]!r},\n")
    out.append("}\n\n")
    out.append(f"MNEMONIC_FALLBACK = {fallback_text!r}\n")

    missing = [v for v in variants if v not in strings]
    dest = Path(__file__).resolve().parent.parent / "src" / "pydasm" / "_mnemonics.py"
    dest.write_text("".join(out), encoding="utf-8")
    print(f"wrote {dest} ({len(variants)} mnemonics, {len(strings)} display strings)")
    if missing:
        # These fall through to MNEMONIC_FALLBACK in Rust too, which is correct
        # for the sentinels (Invalid, NoOpcode, Group, Extension, Prefix, UNDEF).
        print(f"  fall through to {fallback_text!r}: {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
